spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://192.168.3.128:3306/bms-boot?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
  redis:
    host: 192.168.3.128
    port: 6379
    password:
  rabbitmq:
    host: 192.168.3.128
    port: 5672
    username: plei
    password: plei


wokao:
  test: aaaaaaaa